#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': '',
 'entry_points': '[openmdao.component]\nnreltraining.nreltraining.BEMPerf=nreltraining.nreltraining:BEMPerf\nnreltraining.nreltraining.ActuatorDisk=nreltraining.nreltraining:ActuatorDisk\nnreltraining.nreltraining.BEM=nreltraining.nreltraining:BEM\nnreltraining.nreltraining.BladeElement=nreltraining.nreltraining:BladeElement\nnreltraining.nreltraining.AutoBEM=nreltraining.nreltraining:AutoBEM\n\n[openmdao.container]\nnreltraining.nreltraining.BEMPerfData=nreltraining.nreltraining:BEMPerfData\nnreltraining.nreltraining.BEMPerf=nreltraining.nreltraining:BEMPerf\nnreltraining.nreltraining.ActuatorDisk=nreltraining.nreltraining:ActuatorDisk\nnreltraining.nreltraining.FlowConditions=nreltraining.nreltraining:FlowConditions\nnreltraining.nreltraining.BladeElement=nreltraining.nreltraining:BladeElement\nnreltraining.nreltraining.AutoBEM=nreltraining.nreltraining:AutoBEM\nnreltraining.nreltraining.BEM=nreltraining.nreltraining:BEM',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'nreltraining',
 'package_data': {'nreltraining': []},
 'package_dir': {'': 'src'},
 'packages': ['nreltraining'],
 'url': '',
 'version': '1.5',
 'zip_safe': False}


setup(**kwargs)

